# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENT:      ROLE_USER
        ROLE_VENDEUR:     ROLE_VENDEUR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: authentication.handler.login_success_handler
#                default_target_path: /Admin
#                login_path: /

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/administrateur/, role: ROLE_ADMIN }
#        - { path: ^/adminevent/, role: ROLE_ADMIN }
#        - { path: ^/client/, role: ROLE_USER }
#        - { path: ^/ReclamationsC/, role: ROLE_CLIENT }
#        - { path: ^/vendeur/, role: ROLE_VENDEUR }
#        - { path: ^/evenements/, role: ROLE_VENDEUR }
#        - { path: ^/promotions/, role: ROLE_VENDEUR }
#        - { path: ^/promotions/, role: ROLE_VENDEUR }
#        - { path: ^/evenements/{idevenement}/show, role: ROLE_VENDEUR }
#        - { path: ^/evenements/add, role: ROLE_VENDEUR }
#        - { path: ^/evenements/{idevenement}/delete, role: ROLE_VENDEUR }
#        - { path: ^/evenements/{idevenement}/update, role: ROLE_VENDEUR }

