souk_el_medina_produit:
    path:     /ListerProduit
    defaults: { _controller: SoukElMedinaProduitBundle:Produit:ListerProduit }

categorie_mag:
    path:     /categoriemag/{categorie}
    defaults: { _controller: "SoukElMedinaProduitBundle:Produit:RechercheParcategorie" }
    methods:  [GET, POST]


souk_el_medina_detail_produit:
    path:     /DetailsProduits/{idproduit}
    defaults: { _controller: SoukElMedinaProduitBundle:Produit:ShowDetail }